// Generated by CoffeeScript 1.7.1
(function() {
  var changeSubcats;

  String.prototype.capitalize = function() {
    return this.substr(0, 1).toUpperCase() + this.substr(1);
  };

  $(function() {
    return $('#input-category').change(function() {
      var value;
      value = $(this).val();
      if (value === "") {
        return changeSubcats([]);
      } else if (value === '1') {
        return changeSubcats([
          {
            name: '',
            value: ''
          }, {
            name: 'cards',
            value: 1
          }, {
            name: 'autographs',
            value: 2
          }, {
            name: 'sports equipment',
            value: 3
          }
        ]);
      } else if (value === '2') {
        return changeSubcats([
          {
            name: '',
            value: ''
          }, {
            name: 'autographs',
            value: 4
          }, {
            name: 'records',
            value: 5
          }, {
            name: 'toys',
            value: 6
          }
        ]);
      } else if (value === '3') {
        return changeSubcats([
          {
            name: '',
            value: ''
          }, {
            name: 'U.S.',
            value: 7
          }, {
            name: 'international',
            value: 8
          }
        ]);
      } else if (value === '4') {
        return changeSubcats([
          {
            name: '',
            value: ''
          }, {
            name: 'antique',
            value: 9
          }, {
            name: '1980s',
            value: 10
          }, {
            name: 'current day',
            value: 11
          }, {
            name: 'metal',
            value: 12
          }
        ]);
      }
    });
  });

  changeSubcats = function(subcats) {
    var option, subcat, _i, _len, _results;
    $('#input-subcategory').empty();
    _results = [];
    for (_i = 0, _len = subcats.length; _i < _len; _i++) {
      subcat = subcats[_i];
      option = "<option value='" + subcat['value'] + "'>" + (subcat['name'].capitalize()) + "</option>";
      _results.push($('#input-subcategory').append(option));
    }
    return _results;
  };

}).call(this);
